{SPM::SERVICE_NAME}:
    image: rabbitmq:3.7-management-alpine
    environment:
        RABBITMQ_ERLANG_COOKIE: rabbitmqcookienamehere
    volumes:
        - {SPM::PROJECT_NAME}_volumes_{SPM::SERVICE_NAME}-data:/var/lib/rabbitmq
    ports:
        - "5672:5672"
    networks:
        - {SPM::NETWORK_NAME}
    labels:
        traefik.enable: true
        traefik.http.routers.{SPM::SERVICE_NAME}.rule: "Host(`rabbit.${PROJECT_DOMAIN:-example.dev}`)"
        traefik.http.routers.{SPM::SERVICE_NAME}.tls: true
        traefik.http.services.{SPM::SERVICE_NAME}.loadbalancer.server.port: 15672
