{SPM::SERVICE_NAME}:
    build:
        dockerfile: config/docker/dev/{SPM::SERVICE_NAME}/Dockerfile
        context: .
    command:
        - --global.sendAnonymousUsage=false
        - --api.insecure=true
        - --providers.docker=true
        - --providers.docker.exposedByDefault=false
        - --entrypoints.web.address=:80
        - --entrypoints.web.http.redirections.entryPoint.to=https
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entrypoints.https.address=:443
        - --providers.file.directory=/etc/traefik/dynamic_conf/
        - --providers.file.watch=true
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
        - {SPM::NETWORK_NAME}
    labels:
        traefik.enable: true
        traefik.http.routers.{SPM::SERVICE_NAME}.rule: "Host(`proxy.${PROJECT_DOMAIN:-example.dev}`)"
        traefik.http.routers.{SPM::SERVICE_NAME}.tls: true
        traefik.http.services.{SPM::SERVICE_NAME}.loadbalancer.server.port: 8080
