somnambulist:
    cache_dir: '${SOMNAMBULIST_PROJECTS_CONFIG_DIR}/_cache'
    projects_dir: 'Projects'

    templates:
        bundle: ~
        data: 'somnambulist/data-service'
        library: ~
        service: 'somnambulist/symfony-micro-service'
        web: ~
