somnambulist:
    cache_dir: '${SOMNAMBULIST_PROJECTS_CONFIG_DIR}/_cache'
    projects_dir: 'Projects'

    templates:
        library:
            bundle: ~
            client: ~
            library: ~

        service:
            data: 'composer:somnambulist/data-service'
            service: 'composer:somnambulist/symfony-micro-service'
            web: 'composer:symfony/skeleton'
