version: '3.5'

services:
  example-app:
    image: somnambulist/php-fpm:7.4-latest
# requires config files to setup fpm and configure the build steps
#    build:
#      context:    .
#      dockerfile: config/docker/dev/app/Dockerfile
    networks:
      - mycompany_network_backend
# expose a custom port for xdebug debugging <3.0
#    ports:
#      - 9005:9005

  example-web:
    image: nginx:alpine
#    requires config files to link nginx to fpm
#    build:
#      context: .
#      dockerfile: config/docker/dev/web/Dockerfile
    depends_on:
      - example-app
    networks:
      - mycompany_network_backend
    labels:
      traefik.enable: true
      traefik.http.routers.example-web.rule: "Host(`service.example.dev`)"
      traefik.http.routers.example-web.tls: true
      traefik.http.services.example-web.loadbalancer.server.port: 8080
      # note: the container reference needs changing if you change the name above

  example-redis:
    image: redis:alpine
    networks:
      - mycompany_network_backend

networks:
  mycompany_network_backend:
    external: true
